version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"

  - package-ecosystem: "github-actions"
    directory: "/" # Don't change this despite the path being .github/workflows
    reviewers:
      - "Gusto/it-cpe" # Request review from CPE
      - "Gusto/it-infra" # Request review from it-infra
    schedule:
      # Check for updates to GitHub Actions on the first day of the month
      interval: "monthly"
