name "cpe_onepassword"
maintainer "Gusto, Inc."
maintainer_email "noreply@gusto.com"
license "Apache-2.0"
description "Configures 1Password"
version "0.1.0"
supports "mac_os_x"
supports "windows"

depends "cpe_helpers"
