name: Deploy changes to SimpleMDM

on:
  push:
    branches:
      - main
    paths:
      - macos/simplemdm/*.yml
      - ios/simplemdm/*.yml

permissions:
  contents: read

jobs:
  upload:
    name: Sync SimpleMDM profiles
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
        with:
          fetch-depth: 2  # Required to diff HEAD~1

      - name: Construct profile ID map
        shell: python
        run: |
          import json
          import logging
          import os
          import sys
          import requests
          from requests.auth import HTTPBasicAuth

          SIMPLEMDM_API_KEY = os.environ["SIMPLEMDM_API_KEY"]
          SIMPLEMDM_BASE_URL = os.environ["SIMPLEMDM_BASE_URL"]
          SIMPLEMDM_AUTH = HTTPBasicAuth(SIMPLEMDM_API_KEY, "")

          logger = logging.getLogger()

          def list_profile_page(limit, starting_afer=0):
              r = requests.get(
                  url=f"{ SIMPLEMDM_BASE_URL }/custom_configuration_profiles?limit={ limit }&starting_after={ starting_afer }",
                  auth=SIMPLEMDM_AUTH,
              )
              if r.status_code == 200:
                  return r.json()
              else:
                  logger.error(r.text)
                  raise SystemExit

          has_more = True
          start_id = 0
          profile_data = []
          while has_more:
              response = list_profile_page(100, f"{ start_id }")
              data = response["data"]
              profile_data.extend(data)
              has_more = response.get("has_more", None)
              if has_more:
                  start_id = data[-1].get("id")

          profiles_list = {}
          for i in profile_data:
              profiles_list[i["attributes"]["name"]] = i["id"]

          with open("simplemdm_profile_names.json", "w") as f:
              f.write(json.dumps(profiles_list))
        env:
          SIMPLEMDM_API_KEY: ${{ secrets.SIMPLEMDM_API_KEY }}
          SIMPLEMDM_BASE_URL: "https://a.simplemdm.com/api/v1"

      - name: Sync profiles
        run: |
          for profile in $(git diff HEAD~1 --name-only --diff-filter=rd :^.github :^README.md :^.gitignore :^bin :^.pre-commit-config.yaml | uniq)
          do
            echo "Parsing ${profile}"
            profile_name=$(cat $profile | yq ".name")
            user_scope=$(cat $profile | yq ".user_scope")
            attribute_support=$(cat $profile | yq ".attribute_support")
            profile_id=$(cat simplemdm_profile_names.json | jq '."'"$profile_name"'"')

            # Extract profile payload
            envsubst < $profile | yq ".mobileconfig" > mobileconfig

            if [ "$profile_id" = "null" ]
            then
              echo "Creating new profile for ${profile_name}."
              cat mobileconfig | curl --request POST "https://a.simplemdm.com/api/v1/custom_configuration_profiles" \
              --form "name=${profile_name}" --form "user_scope=${user_scope}" \
              --form "attribute_support=${attribute_support}" \
              --form "mobileconfig=@./mobileconfig" \
              --user "${SIMPLEMDM_API_KEY}:"
            else
              echo "Updating existing profile ${profile_id}."
              cat mobileconfig | curl --request PATCH "https://a.simplemdm.com/api/v1/custom_configuration_profiles/${profile_id}" \
              --form "name=${profile_name}" \
              --form "user_scope=${user_scope}" \
              --form "attribute_support=${attribute_support}" \
              --form "mobileconfig=@./mobileconfig" \
              --user "${SIMPLEMDM_API_KEY}:"
            fi
          done
        env:
          SIMPLEMDM_API_KEY: ${{ secrets.SIMPLEMDM_API_KEY }}
          PROFILE_SECRET_WIFI_PASSPHRASE: ${{ secrets.PROFILE_SECRET_WIFI_PASSPHRASE }}

