name: repoclean

on:
  schedule:
    - cron: 00 13 * * 3
  workflow_dispatch:

jobs:
  repoclean:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      MUNKI_COMMIT: "4c4c46132c78ba8a18921023f21f68551cacc939"  # v6.1.0
      PYTHON_VERSION: "3.9.13"  # Match Munki Python
    steps:
      - name: Cache Python ${{ env.PYTHON_VERSION }}
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84  # v3.3.2
        with:
          path: /opt/hostedtoolcache/Python/${{ env.PYTHON_VERSION }}
          key: ${{ runner.os }}-python-cache-${{ env.PYTHON_VERSION }}

      - name: Install and setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1  # v4.3.2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Checkout your Munki LFS repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # v3.6.0
        with:
          repository: replace_with_your_munki_repo
          # GitHub deploy key with read/write access to repo
          ssh-key: ${{ secrets.CPE_MUNKI_LFS_DEPLOY_KEY }}
          ref: refs/heads/main
          path: munki_repo

      - name: Cache Munki code
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84  # v3.3.2
        id: munki-code-cache
        with:
          path: munki
          key: ${{ runner.os }}-munki-code-${{ env.MUNKI_COMMIT }}

      - name: Checkout Munki code
        if: steps.munki-code-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # v3.6.0
        with:
          repository: munki/munki
          ref: ${{ env.MUNKI_COMMIT }}
          path: munki

      - name: Run repoclean
        run: |
          shebang="#!$(which python)"
          sed -i "1 s|.*|${shebang}|" munki/code/client/makecatalogs
          python munki/code/client/repoclean --auto --keep 2 munki_repo

      - name: Push changes
        run: |
          cd munki_repo/
          git config --global user.name "runner"
          git config --global user.email "runner@githubactions.local"
          git checkout -b "repoclean-`date +'%Y-%m-%d'`"
          git add -u pkgsinfo/ pkgs/
          if git diff-index --quiet HEAD; then
            echo "No changes. Nothing to commit.";
          else
            git commit -m "`date +'%Y-%m-%d'` repoclean";
            git push --set-upstream origin "repoclean-`date +'%Y-%m-%d'`";
          fi
