name 'cpe_anyconnect'
maintainer 'Gusto'
maintainer_email 'no-reply@gusto.com'
license 'all_rights'
description 'Manages the XML settings for the Cisco AnyConnect client.'
version '0.1.0'

depends 'cpe_utils'
depends 'cpe_shims'
gem 'xml-simple'
gem 'nokogiri'
